CREATE TABLE `Weapon` (
	`WeaponID` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	`Zone` VARCHAR(255) NOT NULL,
	`Action` VARCHAR(255) NOT NULL,
	`Durability` INT NOT NULL,
	PRIMARY KEY (`WeaponID`)
);

CREATE TABLE `Zone` (
	`ZoneID` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	`Weapon` VARCHAR(255) NOT NULL,
	`Enemy` VARCHAR(255) NOT NULL,
	`EnemyHP` INT NOT NULL,
	PRIMARY KEY (`ZoneID`)
);

CREATE TABLE `Enemy` (
	`EnemyID` VARCHAR(255) NOT NULL,
	`EnemyHP` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	`Zone` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`EnemyID`)
);

CREATE TABLE `Action` (
	`ActionID` VARCHAR(255) NOT NULL,
	`Damage` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ActionID`)
);

ALTER TABLE `Weapon` ADD CONSTRAINT `Weapon_fk0` FOREIGN KEY (`Zone`) REFERENCES `Zone`(`ZoneID`);

ALTER TABLE `Weapon` ADD CONSTRAINT `Weapon_fk1` FOREIGN KEY (`Action`) REFERENCES `Action`(`ActionID`);

ALTER TABLE `Zone` ADD CONSTRAINT `Zone_fk0` FOREIGN KEY (`EnemyHP`) REFERENCES `Enemy`(`EnemyHP`);

ALTER TABLE `Enemy` ADD CONSTRAINT `Enemy_fk0` FOREIGN KEY (`Zone`) REFERENCES `Zone`(`ZoneID`);

